name: Deploy

on:
  workflow_call:

jobs:
  pypi:
    name: PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v6
        name: Download Distribution

        with:
          name: dist
          path: dist

      - name: Deploy
        uses: pypa/gh-action-pypi-publish@release/v1
