name: Test

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ""

permissions:
  contents: read

jobs:
  container:
    name: Container
    runs-on: ubuntu-latest
    timeout-minutes: 30

    container:
      image: rust:1.89-bookworm

    steps:
      - uses: actions/checkout@v7
        name: Checkout Code

        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Install Git
        run: |
          apt-get update
          apt-get install --no-install-recommends --yes git

      - run: cargo install cargo-llvm-cov
        name: Install Coverage Tool

      - run: CARGO_BUILD_JOBS=4 cargo llvm-cov --fail-under-lines 80 --workspace --locked
        name: Run Tests and Coverage

  native:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v7
        name: Checkout Code

        with:
          ref: ${{ inputs.ref || github.ref }}

      - uses: dtolnay/rust-toolchain@stable
        name: Install Rust Toolchain

      - uses: Swatinem/rust-cache@v2
        name: Cache Cargo

      - run: cargo test --workspace --locked
        env:
          CARGO_BUILD_JOBS: "4"
        name: Run Workspace Tests
